server.port=8081
spring.application.name=user-service

spring.datasource.url=jdbc:postgresql://localhost:5432/orderbook_users
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=moj-tajny-sekret-minimalnie-32-znaki-dlugosci!
jwt.expiration=86400000