server {
    listen 80;

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/auth/     { proxy_pass http://user-service:8081; }
    location /api/users/    { proxy_pass http://user-service:8081; }
    location /api/orders/   { proxy_pass http://order-service:8082; }
    location /api/trades/   { proxy_pass http://trade-service:8083; }
    location /api/exchanges/ { proxy_pass http://exchange-service:8084; }
}