server {
    listen 80;

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
    }
    location /api/auth/ {
        proxy_pass http://user-service:8081/auth/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/users/ {
        proxy_pass http://user-service:8081/users/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/orders {
        proxy_pass http://order-service:8082/orders;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/trades {
        proxy_pass http://trade-service:8083/trades;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/exchanges {
        proxy_pass http://exchange-service:8084/exchanges;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}